import { LinearGauge } from "linear-gauge.slint";

component OutputsIndicator inherits HorizontalLayout {
    height: 30px;
    for i in 4: Rectangle {
        background: (i == 0 || i == 3) ? #d87300 : #404041;
    }
}

component DutyCycleGauge inherits LinearGauge {
    height: 8px;
    min_value: 0.0;
    max_value: 100.0;
    track_color: #404041;
    fill_color: #3399ff;
}

component DutyCycleText inherits Text {
    color: #fff;
    font-size: 14px;
    horizontal-alignment: center;
}

component TelemetryRow inherits HorizontalLayout {
    in property <string> voltage;
    in property <string> current;
    spacing: 5px;

    VerticalLayout {
        Text {
            text: voltage;
            color: #fff;
            font-size: 16px;
            horizontal-alignment: center;
        }

        Text {
            text: "V";
            color: #fff;
            font-size: 8px;
            horizontal-alignment: center;
        }
    }

    VerticalLayout {
        Text {
            text: current;
            color: #fff;
            font-size: 16px;
            horizontal-alignment: center;
        }

        Text {
            text: "mA";
            color: #fff;
            font-size: 8px;
            horizontal-alignment: center;
        }
    }
}

component NoteText inherits Text {
    color: #ccc;
    font-size: 20px;
    horizontal-alignment: center;
}

export component ChannelCard {
    in property <string> note: "E#";
    in property <float> voltage: 20.0;
    in property <float> current: 2300.0;
    in property <float> duty_cycle: 50.0;
    in property <bool> is_active: false;
    in property <bool> invert: false;
    callback clicked;

    private property <string> voltage_formatted: Math.round(root.voltage * 10) / 10;
    private property <string> current_formatted: Math.round(root.current);
    private property <string> duty_cycle_formatted: Math.round(root.duty_cycle * 10) / 10;

    width: 100px;
    height: 150px;

    TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {
            root.clicked();
        }
    }

    Rectangle {
        width: parent.width;
        height: parent.height;

        Rectangle {
            OutputsIndicator {
                y: root.invert ? 0px : root.height - self.height;
            }

            Image {
                width: parent.width;
                height: parent.height;
                source: root.invert ? @image-url("assets/channel-card-inverted.png") : @image-url("assets/channel-card.png");
            }
        }

        VerticalLayout {
            padding: 5px;
            padding-top: !root.invert ? 5px : 35px;
            padding-bottom: root.invert ? 5px : 35px;
            spacing: 5px;

            if root.invert: DutyCycleGauge {
                value: root.duty_cycle;
            }
            if root.invert: DutyCycleText {
                text: root.duty_cycle_formatted + " %";
            }
            if root.invert: TelemetryRow {
                voltage: root.voltage_formatted;
                current: root.current_formatted;
            }

            NoteText {
                text: root.note;
            }

            if !root.invert: TelemetryRow {
                voltage: root.voltage_formatted;
                current: root.current_formatted;
            }
            if !root.invert: DutyCycleText {
                text: root.duty_cycle_formatted + " %";
            }
            if !root.invert: DutyCycleGauge {
                value: root.duty_cycle;
            }
        }
    }
}
