import { Button } from "std-widgets.slint";
import { AppStyle } from "style.slint";

export component FaultStatusSection inherits VerticalLayout {
    in property <string> fault: "";

    callback reset_fault;

    alignment: LayoutAlignment.start;
    spacing: AppStyle.spacing_md;

    Rectangle {
        height: AppStyle.spacing_md;
    }

    Text {
        text: "Fault Status";
        font-size: AppStyle.font_size_body;
        color: AppStyle.text_primary;
        font-weight: 600;
    }

    Text {
        text: root.fault == "" ? "None" : root.fault;
        color: root.fault == "" ? AppStyle.status_success : AppStyle.status_error;
        font-size: AppStyle.font_size_small_sm;
    }

    Button {
        text: "Reset Fault";
        enabled: root.fault != "";
        clicked => {
            root.reset_fault();
        }
        width: AppStyle.button_width_md;
    }
}
