export component GaugeRing {
    in property <float> progress: 0.75;
    in property <angle> rotation: 0deg;
    in property <angle> undercut: 90deg;
    in property <int> segments: 12;
    in property <length> stroke_width: 8px;
    in property <brush> track_color: #ddd;
    in property <brush> progress_color: #3399ff;

    min-width: 32px;
    min-height: 32px;

    private property <angle> arc_span: 360deg - undercut;
    private property <angle> start_angle: 180deg + rotation - undercut / 2;

    for i in segments: Rectangle {
        property <angle> this_angle: start_angle + (arc_span * i) / (segments - 1);
        property <length> r: (parent.width + parent.height) / 4 - (stroke_width / 2);

        width: stroke_width;
        height: (parent.width + parent.height) / 24;
        x: parent.width / 2 - self.width / 2 + r * Math.cos(this_angle);
        y: parent.height / 2 - self.height / 2 + r * Math.sin(this_angle);
        border-radius: stroke_width / 2;
        background: i < progress * segments ? progress_color : track_color;
    }
}
