import { GaugeRing } from "gauge-ring.slint";

export component Gauge {
    in property <float> min_value: 0.0;
    in property <float> max_value: 100.0;
    in property <float> value: 50.0;
    in property <int> value_precision: 0;
    in property <string> unit: "V";
    in property <angle> rotation: 0deg;
    in property <angle> undercut: 90deg;
    in property <length> stroke_width: 8px;
    in property <brush> track_color: #dddddd;
    in property <brush> progress_color: #3399ff;
    in property <brush> text_color: #ffffff;

    min-width: 32px;
    min-height: 32px;

    private property <float> safe_value: Math.max(min_value, Math.min(value, max_value));
    private property <float> progress: (safe_value - min_value) / Math.max(0.00001, max_value - min_value);
    private property <length> min_size: Math.min(self.width, self.height);

    GaugeRing {
        progress: root.progress;
        rotation: root.rotation;
        undercut: root.undercut;
        stroke_width: root.stroke_width;
        track_color: root.track_color;
        progress_color: root.progress_color;
        width: parent.width;
        height: parent.height;
    }

    Text {
        property <float> k: 0.1;
        property <float> base_offset: k * Math.sin(root.undercut / 2) * ((parent.height / 1px) / 2);
        property <float> offset_x: base_offset * Math.sin(root.rotation);
        property <float> offset_y: -base_offset * Math.cos(root.rotation);

        text: "value";
        color: root.text_color;
        font-size: 10px;
        x: parent.width / 2 - self.width / 2 + offset_x * 1px;
        y: parent.height / 2 - self.height / 2 + offset_y * 1px;
    }

    Text {
        private property <angle> unit_angle: 90deg + rotation;
        private property <float> unit_radius: 0.7;

        text: root.unit;
        color: root.text_color;
        font-size: 8px;
        x: parent.width / 2 + unit_radius * min_size / 2 * Math.cos(unit_angle) - self.width / 2;
        y: parent.height / 2 + unit_radius * min_size / 2 * Math.sin(unit_angle) - self.height / 2;
    }
}
