export component LinearGauge {
    in property <float> min_value: 0.0;
    in property <float> max_value: 100.0;
    in property <float> value: 50.0;
    in property <brush> track_color: #404041;
    in property <brush> fill_color: #3399ff;

    private property <float> normalized_value: Math.max(0, Math.min(1, (root.value - root.min_value) / Math.max(0.0001, root.max_value - root.min_value)));

    Rectangle {
        x: 0px;
        y: 0px;
        width: parent.width;
        height: parent.height;
        background: root.track_color;
    }

    Rectangle {
        x: 0px;
        y: 0px;
        width: parent.width * normalized_value;
        height: parent.height;
        background: root.fill_color;
    }
}
